config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :welcomes
  resources :teams, only: (:index)
  resources :contacts, only: (:index)
  resources :users
  resources :gossips
  resources :cities
  resources :sessions, only:[:index, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :JoinTableTagGossips
  has_many :tags, through: :JoinTableTagGossips
  validates :title, presence: true
  validates :content, presence: true
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/lier_private_message_user.rb
class LierPrivateMessageUser < ApplicationRecord
  belongs_to :user
  belongs_to :private_message
  
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :LierPrivateMessageUsers
  has_many :receivers,through: :LierPrivateMessageUsers,source: :user
  belongs_to :sender, class_name: "User"
  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :JoinTableTagGossips
  has_many :gossips, through: :JoinTableTagGossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_secure_password

  has_many :LierPrivateMessageUsers
  has_many :received_messages,through: :LierPrivateMessageUsers, source: :private_message
  has_many :sent_messages, foreign_key: 'sender_id',class_name: "PrivateMessage"
  
  #validates :first_name, presence: true
  #validates :description, presence: true
  #validates :email,
    #presence: true,
    #uniqueness: true,
    #format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/Cities_controller.rb
class CitiesController < ApplicationController 
  
  def index
    @city = City.all
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :alert
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController 
  
    def index
    end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController 
  before_action :authenticate_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :good_user, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.all 
  end

  

  def show
    @gossip = params[:id]
    @gossip_id = Gossip.find(params[:id])
    @get_city_name = City.find(@gossip_id.user.city_id).name
  end
   
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(post_params)
    @gossip.user = User.find_by(id: session[:user_id])
    
    if @gossip.save
      puts "saved"
      redirect_to gossips_path, :notice => 'Mefait accompli'
    else
      puts "hmmm...ca n'a pas fonctionne,essaie encore"
      puts @gossip.errors.messages
      render 'new'
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params)
    redirect_to gossips_path
  end 

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def post_params
    params.permit(:title, :content)
  end
      
  def authenticate_user
      unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to new_session_path
      end
  end

  def good_user 
      if session[:user_id] != Gossip.find(params[:id]).user_id 
        flash[:danger] = "Mauvais utilisateur"
        redirect_to gossips_path
      end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index 
    end

    def new
        session = User.new
    end

    def create
        # cherche s'il existe un utilisateur en base avec l’e-mail
        user = User.find_by(email: params[:email])

        puts params[:email]
        puts params[:password]
          
        # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to gossips_path
            # redirige où tu veux, avec un flash ou pas
          
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to gossips_path
    end
    
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def index
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(post_params)
    
    if @user.save
      puts "saved"
      redirect_to gossips_path, :notice => 'Mefait accompli'
    else
      puts "hmmm...ca n'a pas fonctionne,essaie encore"
      puts @user.errors.messages
      render 'new'
    end

  end

  private

  def post_params
    params.permit(:first_name, :last_name, :description, :email, :age, :city_id, :password)
  end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController 

  def show
    @first_name = params[:first_name]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
     User.find_by(id: session[:user_id])
    end
 
    def log_in(user)
     session[:user_id] = user.id
    end

    def logged_in?
        if session[:user_id].nil?
            return true
        else 
            return false
        end
    end
 
 end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/index.html.erb
<h1><%= @city.name %></h1> 

<p> Les potins lies a la ville sont les suivants </p>] 

<div class="card-columns">
  <% @gossips.each do |gossip|%>
    <div class="card" style="max-width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> Title : <%= gossip.title %></h5> 
        <p class="card-text"><small class="text-muted"> Author <%= gossip.user.first_name %></small></p>
        <%= link_to "voir le gossip", gossip_path(gossip.id), class:"btn btn-primary" %>
        <%= link_to "Editer le gossip", edit_gossip_path(gossip.id), class:"btn btn-default" %>
        <a href="<%=  gossip_path(gossip.id) %>" class="btn btn-danger"  data-confirm="etes-vous surs ?" data-method="DELETE"> Supprimer </a>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<h1> Want to contact us?<h1>
<p> Here is our contact contact@gossip.com </p>

app/views/gossips/edit.html.erb
<h1> Editer le gossip <%= @gossip.title %></h1> 

<!-- ... -->

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= f.text_field :title, class: 'form-control' %>
    <br /> <br />
  </div>

  <div class="form-group">
    <%= label_tag 'Contenu' %>
    <%= f.text_area :content,  class: 'form-control' %>
    <br /> <br />
  </div>

  <div class="form-group">
    <%= submit_tag "Edit Gossip", class:'btn btn-primary' %>
    </div>
<% end %>

<!-- ... -->

<% if @gossip.errors.any? %>
<p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
<ul>
  <% @gossip.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

 

app/views/gossips/index.html.erb
<h1> Bienvenue sur The Gossip Project ! </h1> 

<div class ="container" style="padding-top: 5rem;">

<br>
<%= button_to "Creer un potin", new_gossip_path, :method => "get", class:'btn btn-success' %>
<br>

<div class="card-columns">
  <% @gossips.each do |gossip|%>
    <div class="card" style="max-width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> Title : <%= gossip.title %></h5> 
        <p class="card-text"><small class="text-muted"> Author <%= gossip.user.first_name %></small></p>
        <%= link_to "voir le gossip", gossip_path(gossip.id), class:"btn btn-primary" %>
        <%= link_to "Editer le gossip", edit_gossip_path(gossip.id), class:"btn btn-default" %>
        <a href="<%=  gossip_path(gossip.id) %>" class="btn btn-danger"  data-confirm="Etes-vous surs de vouloir supprimer le gossip ?" data-method="DELETE"> Supprimer </a>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<h1> Raconte-nous un nouveau potin ! </h1>
<p> on aime les details </p>


<!-- ... -->

<%= form_tag gossips_path(action: 'create'), method: "post" do %>

  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Create Gossip", class: 'btn btn-primary' %>

<% end %>

<!-- ... -->

<% if @gossip.errors.any? %>
<p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
<ul>
  <% @gossip.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/gossips/show.html.erb
<div class="card">
    <div class="card-header">
         Potin numéro <%= @gossip %>: 
    </div>

    <div class="card-body">
        <h6 class="card-title"> <U>le titre du potin est:</U> <%=@gossip_id.title %> </h6>
            <h7> l'auteur est: <%= link_to "#{@gossip_id.user.first_name}", user_path%></h7>
            <p class="card-text"> et vient de : <%= link_to "#{@get_city_name}", city_path%></p>
            <p> ce potin a été crée le: <%=@gossip_id.created_at %> </p> </br>
            <p><U>Contenu du potin:</U> </p> </br>
            <p> <%=@gossip_id.content %> </p> </br>
            <%=link_to "Editer l'article", edit_gossip_path, class:"btn btn-success" %>
            <a href="<%=  gossip_path(@gossip) %>" class="btn btn-danger"  data-confirm="Etes-vous sur ?" data-method="DELETE"> Supprimer </a>
    </div>
</div>    
    </br>
<div class="card">
    <div class="card-header">
    Commente tes potins favoris:
    </div>
    <div class="card-body">
    <div class="form-group">
        <%= form_tag gossip_path(@gossip) do %>
            </br>
            <label>Contenu:</label>
            </br>
            <%=text_area_tag :content%>
        </div>

        <div class="form-froup">
            <button type="submit" class="btn btn-primary">Commenter</button>
        </div>

        <% end %>    
        
    </div>
</div>

app/views/users/new.html.erb
<div class="card">
  <div class="card-body">
  
    <h1>Tu veux devenir une commère? </h1>
    <p>Tous ce que tu nous confies, reste entre nous ;)</p>
    </br>

    <%= form_tag users_path(action: "create"), method: "post" do %>

        <%= label_tag "prénom:" %> </br>
        <%= text_field_tag "first_name", @first_name %>
        <br /> <br />

        <%= label_tag "nom:" %> </br>
        <%= text_field_tag "last_name", @last_name %>
        <br /> <br />

        <%= label_tag "description:" %> </br>
        <%= text_area_tag "description", @description %>
        <br /> <br />

        <%= label_tag "email:" %> </br>
        <%= text_field_tag "email", @email %>
        <br /> <br />

        <%= label_tag "age:" %> </br>
        <%= text_field_tag "age", @age.to_i %>
        <br /> <br />

        <%= label_tag "choisi un numéro de ville entre 1 et 10:" %> </br>
        <%= text_field_tag "city_id", @city_id.to_i %>
        <br /> <br />

        <%= label_tag "mot de passe:" %> </br>
        <%= text_field_tag "password", @password %>
        <br /> <br />

        <%= submit_tag "Créer ton profile" %>
        
    <% end %>

        </br>

        <% if @user.errors.any? %>
            <p>Nous n'avons pas réussi à créer le profile pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
                <div class="alert alert-danger" role="alert">
                <li><%= message %></li>
                </div>
        <% end %>
            </ul>

    <% end %>
   
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1> 

<p> Les informations du user
  <li> voici son email : <%= @user.email %> 
  <li> son age : <%= @user.age %>
  <li> sa description : <%= @user.description %>
  <li> le nom de sa ville : <%= @user.city %>

  <%= link_to "Pour les potins lies a sa ville, c'est par ici..." city_path(city_id), class: btn btn-primary %>
  
</p>

app/views/welcome/index.html.erb
<h1> Bienvenue <%= @first_name %>  sur The Gossip Project! </h1>
<p> Shut... </p>