config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :welcomes
  resources :teams, only: (:index)
  resources :contacts, only: (:index)
  resources :users
  resources :gossips
  resources :cities
  resources :sessions, only:[:index, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :JoinTableTagGossips
  has_many :tags, through: :JoinTableTagGossips
  validates :title, presence: true
  validates :content, presence: true
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/lier_private_message_user.rb
class LierPrivateMessageUser < ApplicationRecord
  belongs_to :user
  belongs_to :private_message
  
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :LierPrivateMessageUsers
  has_many :receivers,through: :LierPrivateMessageUsers,source: :user
  belongs_to :sender, class_name: "User"
  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :JoinTableTagGossips
  has_many :gossips, through: :JoinTableTagGossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_secure_password

  has_many :LierPrivateMessageUsers
  has_many :received_messages,through: :LierPrivateMessageUsers, source: :private_message
  has_many :sent_messages, foreign_key: 'sender_id',class_name: "PrivateMessage"
  
  #validates :first_name, presence: true
  #validates :description, presence: true
  #validates :email,
    #presence: true,
    #uniqueness: true,
    #format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/Cities_controller.rb
class CitiesController < ApplicationController 
  
  def index
    @city = City.all
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController 
  
    def index
    end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController 
  before_action :authenticate_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :good_user, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.all 
  end

  

  def show
    @gossip = params[:id]
    @gossip_id = Gossip.find(params[:id])
    @get_city_name = City.find(@gossip_id.user.city_id).name
  end
   
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(post_params)
    @gossip.user = User.find_by(id: session[:user_id])
    
    if @gossip.save
      puts "saved"
      redirect_to gossips_path, :notice => 'Mefait accompli'
    else
      puts "hmmm...ca n'a pas fonctionne,essaie encore"
      puts @gossip.errors.messages
      render 'new'
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params)
    redirect_to gossips_path
  end 

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def post_params
    params.permit(:title, :content)
  end
      
  def authenticate_user
      unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to new_session_path
      end
  end

  def good_user 
      if session[:user_id] != Gossip.find(params[:id]).user_id 
        flash[:danger] = "Mauvais utilisateur"
        redirect_to gossips_path
      end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index 
    end

    def new
        session = User.new
    end

    def create
        # cherche s'il existe un utilisateur en base avec l’e-mail
        user = User.find_by(email: params[:email])

        puts params[:email]
        puts params[:password]
          
        # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to gossips_path
            # redirige où tu veux, avec un flash ou pas
          
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to gossips_path
    end
    
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def index
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(post_params)
    
    if @user.save
      puts "saved"
      redirect_to gossips_path, :notice => 'Mefait accompli'
    else
      puts "hmmm...ca n'a pas fonctionne,essaie encore"
      puts @user.errors.messages
      render 'new'
    end

  end

  private

  def post_params
    params.permit(:first_name, :last_name, :description, :email, :age, :city_id, :password)
  end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController 

  def show
    @first_name = params[:first_name]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
     User.find_by(id: session[:user_id])
    end
 
    def log_in(user)
     session[:user_id] = user.id
    end

    def logged_in?
        if session[:user_id].nil?
            return true
        else 
            return false
        end
    end
 
 end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>

  <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Gossip Project", gossips_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", gossips_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Team", teams_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact", contacts_path, class: "nav-link" %>
          </li>

          <% if logged_in? == true %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Inscription/Conenxion
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Inscription", new_user_path, class: "dropdown-item" %>
                <%= link_to "Connexion", new_session_path, class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div> 
    </nav>

    <% flash.each do |type, msg| %>
      <div class="alert alert-success" role="alert">
        <%= msg %>
      </div>
    <% end %>
  </header>

  <body>
    <div class ="container" style="padding-top: 5rem;">
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1> Want to contact us?<h1>
<p> Here is our contact contact@gossip.com </p>

app/views/static_pages/team.html.erb
<h1> Who developed this amazing website?<h1>

<p> THP students!<br> based on the amazing work of Alex, this new version of Gossip Project has been developed by 
  <li> Emma with the help of
  <li> Vincent
  <li> Louison
  <li> Jeremy
  <li> Benedicte
  <li> Nabil
  <li> Samir
</p>

app/views/static_pages/welcome.html.erb
<h1> Bienvenue <%= @first_name %>  sur The Gossip Project! </h1>
<p> Shut... </p>